[package]
name = "wgpu-egui-tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
egui = "0.31.1"
egui-wgpu = "0.31.1"
egui-winit = "0.31.1"
pollster = "0.4.0"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1.41"
wgpu = "24.0.3"
winit = "0.30.10"
