[package]
name = "image-texture"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = "1.23.0"
image = "0.25.6"
reqwest = "0.12.15"
tokio = { version = "1.45.0", features = ["full"] }
tracing-subscriber = "0.3.19"
wgpu-egui-tokio = { path = "../../" }
